# Generated by Django 4.1.7 on 2023-03-10 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "pull_requests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), size=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("description", models.TextField()),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Backlog"),
                            (1, "TODO"),
                            (2, "Work In Progress"),
                            (3, "Code Review"),
                            (4, "Testing"),
                            (5, "Done"),
                            (6, "Cancelled"),
                        ]
                    ),
                ),
            ],
        ),
    ]
