# Generated by Django 4.1.7 on 2023-03-10 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        ("projects", "0002_initial"),
        ("boards", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="boards.board",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="children",
            field=models.ManyToManyField(related_name="parent", to="tasks.task"),
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(to="boards.label"),
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="related_tasks",
            field=models.ManyToManyField(to="tasks.task"),
        ),
        migrations.AddField(
            model_name="task",
            name="reviewers",
            field=models.ManyToManyField(
                related_name="tasks_to_review", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="tasks.taskstatus",
            ),
        ),
    ]
